name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache Rust packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
        path: |
          ~/.cargo
    - name: Build
      run: cargo build --verbose --release
    - name: Install elf2uf2-rs
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev 
        cargo install elf2uf2-rs
    - name: Generate uf2 file
      run: elf2uf2-rs -v target/thumbv6m-none-eabi/release/subtone
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: firmware-binaries
        path: |
          target/thumbv6m-none-eabi/release/subtone
          target/thumbv6m-none-eabi/release/subtone.uf2
